Crud api
GlebLudis/typescript_coans pull request #2
Opened 2022-01-22 12:41 UTC by GlebLudis

2022-01-23 17:35 UTC, AntiHero requested changes

2022-01-23 17:35 UTC, AntiHero commented on package.json
> +    "@firebase/database-types": "^0.9.4",
это всё же в devDep должно быть

2022-01-23 17:35 UTC, AntiHero commented on src/fireBaseCrud.test.ts
> +  await firebase.database().ref(calendar.fireBasePlace).remove();
лучше и после всех тестов очищать тестовую базу данных

2022-01-23 17:35 UTC, AntiHero commented on src/fireBaseCrud.test.ts
> +      await (await locateFireBase.get()).val()
можешь пожалуйста рассказать для чего здесь два await?

2022-01-23 17:35 UTC, AntiHero commented on src/fireBaseCrud.ts
> +      this.tasksId = Object.keys(await (await locateFireBase.get()).val());
то же самое здесь и далее, для чего ты используешь два await?

2022-01-23 17:35 UTC, AntiHero commented on src/localStorageCrud.ts
> +    storage: Task[] = [];
для чего тебе здесь storage?

2022-01-23 17:35 UTC, AntiHero commented on src/localStorageCrud.ts
> +    async read(id: Task["id"]): Promise<Task> {
это не асинхронный метод, CRUD мы должны реализовать таким образом, чтобы методы были асинхронными, в данном случае это не так

2022-01-23 17:35 UTC, AntiHero commented on src/localStorageCrud.ts
> +      if (localStorage.getItem("Calendar") !== undefined) {
т.е. при каждом запуске твоей программы LS будет перезаписываться пустым массивом? Можешь пожалуйста объяснить, для чего тогда использовать LocalStorage?

2022-01-23 17:35 UTC, AntiHero commented on src/localStorageCrud.ts
> +    async delete(id: Task["id"]): Promise<void> {
это тоже не асинхронный метод

2022-01-25 12:12 UTC, GlebLudis commented on src/fireBaseCrud.test.ts
> +      await (await locateFireBase.get()).val()
так предложил ESLint) исправлю

2022-01-25 12:36 UTC, GlebLudis commented on src/localStorageCrud.ts
> +      if (localStorage.getItem("Calendar") !== undefined) {
Исправил, я хотел сделать проверку, если ls пустой то создать массив где будет храниться календарь с задачами.

2022-01-25 12:46 UTC, GlebLudis commented on src/fireBaseCrud.test.ts
> +  await firebase.database().ref(calendar.fireBasePlace).remove();
готово

2022-02-03 18:45 UTC, merged